
# ************************************************************************************************************
#                                             Server: ServerProperties
# ************************************************************************************************************
server:
  port: 9090
  ssl: # TODO

  compression:
    enabled: true
    min-response-size: 50KB

  servlet:
    context-path: demo
    context-parameters: # TODO

    session:
      cookie:
        http-only: true
        secure: false

  tomcat:
    max-http-post-size: 4MB


spring:
  # **********************************************************************************************************
  #                                           Web: Template Engine
  # **********************************************************************************************************
  freemarker:
    settings:
      # TODO

  # **********************************************************************************************************
  #                                           i18n: MessageSourceProperties
  # **********************************************************************************************************
  messages:
    basename: messages,config.i18n.messages

  # **********************************************************************************************************
  #                                           Web: File Upload
  # **********************************************************************************************************
  servlet:
    multipart:
      location: uploads/
      max-file-size: 10MB
      max-request-size: 12MB

  # **********************************************************************************************************
  #                                           Web: MVC
  # **********************************************************************************************************
  mvc:
    static-path-pattern: /resources/** # 设定 -> 静态资源 URL 访问路径

  # **********************************************************************************************************
  #                                           Web: Static Resources
  # **********************************************************************************************************
  resources:
    chain:
      compressed: true
      strategy:
        content:
          enabled: true
          paths: # TODO

        fixed:
          enabled: true
          paths: # TODO
          version: # TODO

    cache:
      cachecontrol:
        max-age: 1h



# ************************************************************************************************************
#                                             DataSource
# ************************************************************************************************************
app:
  sql-database:
    primary:
      datasource:
        name: primary
        url: jdbc:mysql://******:3306/***
        username: !********
        password: !********
        driver-class-name: com.mysql.jdbc.Driver
        configuration:
          maximum-pool-size: 30
      jpa:
        show-sql: true
        properties:
          hibernate.jdbc.batch_size: 500
          hibernate.dialect: org.hibernate.dialect.MySQLDialect
      jpa-hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    secondary:
      datasource:
        name: primary
        url: jdbc:mysql://******:3306/***
        username: !********
        password: !********
        driver-class-name: com.mysql.jdbc.Driver
        max-total: 10
      jpa:
        show-sql: true
        properties:
          hibernate.dialect: org.hibernate.dialect.MySQLDialect
      jpa-hibernate:
        ddl-auto: none
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
